---
- name: create user launchd directory
  file: path=~/Library/LaunchAgents state=directory recurse=yes

- name: add launchd links
  file: path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist state=link force=yes
  with_items: "{{ homebrew_services }}"

- name: check launchd
  shell: launchctl list
  register: launchd_result
  # always_run: yes - deprecated, use check_mode=no instead
  check_mode: no
  changed_when: false

- name: load launchd links
  command: launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
  when: item not in launchd_result.stdout
  with_items: "{{ homebrew_services }}"
