---
- name: install taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - argon/mas
    - cloudfoundry/tap
    # for older java versions
    - caskroom/versions

- name: install prerequisite casks
  homebrew_cask: name={{ item }} state=present
  when: not lookup("env", "CI")
  ignore_errors: yes
  with_items:
    # for maven
    - java
    - java8

- name: install brews
  homebrew: name={{ item }} state=present
  ignore_errors: yes
  with_items:
    - git
    - python
    - mas
    - memcached
    - mysql
    - node
    - rabbitmq
    - rbenv
    - redis
    - wget
    - cf-cli
    - liquibase
    - mongodb
    - maven

- name: get installed apps from app store
  command: mas list
  when: not lookup("env", "CI")
  register: mas_result
  # always_run: yes - deprecated, use check_mode=no instead
  check_mode: no
  changed_when: false

- name: install apps from app store
  command: mas install {{ item }}
  ignore_errors: yes
  when: not mas_result.skipped|default(false) and "{{ item }}" not in mas_result.stdout
  with_items:
    - 506189836 # Harvest
    - 413965349 # Soulver
    - 587512244 # Kaleidoscope
    - 603117688 # CCMenu
    - 775737590 # iA Writer
    - 411643860 # DaisyDisk
    - 497799835 # Xcode
    - 924726344 # Deliveries
    - 975937182 # Fantastical 2
    - 407963104 # Pixelmator
    - 557168941 # Tweetbot
    - 409183694 # Keynote
    - 409201541 # Pages
    - 409203825 # Numbers

- name: install casks
  homebrew_cask: name={{ item }} state=present
  when: not lookup("env", "CI")
  ignore_errors: yes
  with_items:
    - alfred
    - atom
    - charles
    - dash
    - docker
    - google-chrome
    - firefox
    - java
    - kaleidoscope
    - libreoffice
    - paparazzi
    - paw
    - sequel-pro
    - sketch
    - skype
    - textmate
    - sourcetree
    - transmit
    - vlc
    - sts
    - webstorm
    - slack
    - caffeine
    - android-studio

- name: install pip packages
  pip: name={{ item }} state=present
  with_items:
    - ansible
    - mysqlclient
    - python-memcached
    - virtualenv

- name: install npm packages
  npm: name={{ item }} global=yes state=present
  with_items:
    - bower

- name: install gem packages
  gem: name={{ item }} state=present
  with_items:
    - bundler
